### ISSUE TITLE
where is void a transactions example, can you please provide it?

### ISSUE THREAD

**Issue by vivekp56** [intuit/PHP-Payments-SDK#1]
Hi,

I can see there is an API available, for Void a transaction,
https://developer.intuit.com/app/developer/qbpayments/docs/api/resources/all-entities/charges#void-a-transaction

can you please provide demo example for Void a transaction, as I am using this Payments SDK and I am not able to find any Void functions in, https://github.com/intuit/PHP-Payments-SDK/blob/master/tests/ChargeTest.php

Thank You

**Comment by hlu2** [comment]
Sure. I will create one.

**Comment by Martin89PL** [comment]
HI! I created PR for this: https://github.com/intuit/PHP-Payments-SDK/pull/6/files

**Comment by hlu2** [comment]
@vivekp56 @Martin89PL has created it. I will close this one.

**Comment by vivekp56** [comment]
@hlu2  @Martin89PL  Thanks for the support.
