### ISSUE TITLE
sample/Interceptorexample.php dosnt Log anything

### ISSUE THREAD

**Issue by sharkbit** [intuit/PHP-Payments-SDK#18]
Line 9 has wrong libraries,  should be:
use QuickBooksOnline\Payments\Interceptors\{StackTraceLoggerInterceptor, RequestResponseLoggerInterceptor, ExceptionOnErrorInterceptor};

but that still dosnt get anything to log.  It's like they are not being triggered.   Using pretty much exact code from sample.

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://epay724.com))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….
