### ISSUE TITLE
Charge request returns not existing fields (on SandBox)

### ISSUE THREAD

**Issue by ididenko** [intuit/PHP-Payments-SDK#20]
Response from createChargeRequest 
`{"created":"2020-06-10T14:53:24Z","status":"CAPTURED","amount":"1.00","currency":"USD","card":{"number":"xxxxxxxxxxxx0004","name":"Didenko Eugene","address":{"city":"sdf","streetAddress":"sdf","postalCode":"61000"},"cardType":"MasterCard","expMonth":"11","expYear":"2023"},"avsStreet":"Pass","avsZip":"Pass","cardSecurityCodeMatch":"NotAvailable","id":"E562VVKKAC2Z","context":{"reconBatchID":"420200610 1Q07539999999968171687AUTO04","mobile":false,"paymentGroupingCode":"4","txnAuthorizationStamp":"1591800804","paymentStatus":"Completed","merchantAccountNumber":"9999999968171687","clientTransID":"amyxghdp","deviceInfo":{},"recurring":false,"isEcommerce":true},"authCode":"715902"}`

Error: reconBatchID property doesn't exist in Context Class

**Comment by abisalehalliprasan** [comment]
We have handled this in our latest release [v1.0.8](https://github.com/intuit/PHP-Payments-SDK/tree/v1.0.8)
