### ISSUE TITLE
Exception: Property name: [status] is not a valid field for: [QuickBooksOnline\Payments\Modules\Card]. Please check your keys.

### ISSUE THREAD

**Issue by rogerd330** [intuit/PHP-Payments-SDK#21]
Starting at ~7:45pm (central time) I started getting the exception when calling PaymentClient->getAllCardsFor($customer_id).

My simply adding the $status property to the Modules\Card class, the error goes away and requests seem to be processing normally.

I'm guessing the API team released something new today for the SDK to handle.

**Comment by hillj17** [comment]
Same thing happened to me and I added the same change to Modules\Card, and it fixed it.  It seems like there are others that have had similar issues, and the devs haven't released a new package yet, although they released the server-side changes.

**Comment by abisalehalliprasan** [comment]
We have handled this in our latest release [v1.0.8](https://github.com/intuit/PHP-Payments-SDK/tree/v1.0.8)
