### ISSUE TITLE
I getting error in sandbox - "Property name: [reconBatchID] is not a valid field for: [QuickBooksOnline\Payments\Modules\Context]. Please check your keys."

### ISSUE THREAD

**Issue by Atranaz** [intuit/PHP-Payments-SDK#23]
I try to check this API through sandbox pass my access token when card detail is not ok it through proper error.

But unfortunately when details are correct apt throw this error

"Property name: [reconBatchID] is not a valid field for: [QuickBooksOnline\Payments\Modules\Context]. Please check your keys."

**Comment by bsivalingam** [comment]
@Atranaz thanks for bringing this up. I am checking with the team.
