### ISSUE TITLE
"Get a Card" doesn't appear to be implemented

### ISSUE THREAD

**Issue by rogerd330** [intuit/PHP-Payments-SDK#9]
This request doesn't appear to have a function available.
https://developer.intuit.com/app/developer/qbpayments/docs/api/resources/all-entities/cards#get-a-card

I have a local copy that I can send up as a PR, I just wanted to point it out first if that's ok.

Thanks!

**Comment by hlu2** [comment]
@rogerd330 Somehow it is missing. If you can send a PR, I will review and merge!
